// Enums for agent-related types

export enum AgentStatus {  
  PENDING_WALLET = 'PENDING_WALLET',
  PENDING_DID = 'PENDING_DID',
  PENDING_VC = 'PENDING_VC',
  PENDING_REGISTRATION = 'PENDING_REGISTRATION',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  ERROR = 'ERROR',
  MAINTENANCE = 'MAINTENANCE',
}

export enum AgentVcIssueStatus {
  PENDING = 'PENDING',
  ISSUED = 'ISSUED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
  FAILED_TO_ISSUE = 'FAILED_TO_ISSUE'
}

export enum AgentType {
  PERSONAL = 'PERSONAL',
  BUSINESS = 'BUSINESS',
  GOVERNMENT = 'GOVERNMENT',
  EDUCATIONAL = 'EDUCATIONAL',
  NON_PROFIT = 'NON_PROFIT',
  COMMUNITY = 'COMMUNITY',
  ENTERPRISE = 'ENTERPRISE',
  RESEARCH = 'RESEARCH',
  INDUSTRIAL = 'INDUSTRIAL',
  OTHER = 'OTHER'
}

export enum AgentCategory {
  TRAVEL = 'TRAVEL',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  CRYPTO = 'CRYPTO',
  CONTENT_CREATION = 'CONTENT_CREATION',
  DATA_ANALYTICS = 'DATA_ANALYTICS',
  MARKET_INTELLIGENCE = 'MARKET_INTELLIGENCE',
  SECURITY = 'SECURITY',
  COMPLIANCE = 'COMPLIANCE',
  GOVERNANCE = 'GOVERNANCE',
  AUTOMATION = 'AUTOMATION',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  OTHERS = 'OTHERS'
}

export enum AgentCapability {
  FLIGHT_SEARCH = 'FLIGHT_SEARCH',
  FLIGHT_BOOKING = 'FLIGHT_BOOKING',
  HOTEL_BOOKING = 'HOTEL_BOOKING',
  CAR_RENTAL = 'CAR_RENTAL',
  TRAVEL_ITINERARY_MANAGEMENT = 'TRAVEL_ITINERARY_MANAGEMENT',
  TRAVEL_EXPENSE_MANAGEMENT = 'TRAVEL_EXPENSE_MANAGEMENT',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  PERSONAL_ASSISTANT = 'PERSONAL_ASSISTANT',
  SOCIAL_MEDIA_MANAGEMENT = 'SOCIAL_MEDIA_MANAGEMENT',
  CRYPTO_TRADING = 'CRYPTO_TRADING',
  CRYPTO_WALLET_MANAGEMENT  = 'CRYPTO_WALLET_MANAGEMENT',
  CRYPTO_ASSET_ANALYTICS = 'CRYPTO_ASSET_ANALYTICS',
  CRYPTO_TRANSACTION = 'CRYPTO_TRANSACTION',
  TEXT_GENERATION = 'TEXT_GENERATION',
  IMAGE_GENERATION = 'IMAGE_GENERATION',
  AUDIO_GENERATION = 'AUDIO_GENERATION',
  VIDEO_GENERATION = 'VIDEO_GENERATION',
  CODE_GENERATION = 'CODE_GENERATION',
  LANGUAGE_TRANSLATION = 'LANGUAGE_TRANSLATION',
  SUMMARIZATION_CONTENT_EXTRACTION = 'SUMMARIZATION_CONTENT_EXTRACTION',
  KNOWLEDGE_RETRIEVAL_REASONING = 'KNOWLEDGE_RETRIEVAL_REASONING',
  DATA_INTEGRATION_VISUALIZATION = 'DATA_INTEGRATION_VISUALIZATION',
  MARKET_INTELLIGENCE = 'MARKET_INTELLIGENCE',
  TRANSACTION_ANALYTICS = 'TRANSACTION_ANALYTICS',
  SMART_CONTRACT_AUDIT = 'SMART_CONTRACT_AUDIT',
  GOVERNANCE_FACILITATION = 'GOVERNANCE_FACILITATION',
  SECURITY_MONITORING = 'SECURITY_MONITORING',
  COMPLIANCE_REGULATORY_ANALYSIS = 'COMPLIANCE_REGULATORY_ANALYSIS',
  FRAUD_DETECTION_PREVENTION = 'FRAUD_DETECTION_PREVENTION',
  MULTI_AGENT_COORDINATION = 'MULTI_AGENT_COORDINATION',
  API_INTEGRATION_ORCHESTRATION = 'API_INTEGRATION_ORCHESTRATION',
  WORKFLOW_AUTOMATION = 'WORKFLOW_AUTOMATION',
}
